version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mdm-postgres
    environment:
      POSTGRES_DB: mdm_db
      POSTGRES_USER: mdm_user
      POSTGRES_PASSWORD: mdm_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mdm_user -d mdm_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mdm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: mdm-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mdm_db
      SPRING_DATASOURCE_USERNAME: mdm_user
      SPRING_DATASOURCE_PASSWORD: mdm_password
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:


